Repository streamnative/pulsar-spark, pull requests merged in 2019-07, with the labels that each got.

#9 Cleanup dependencies
  .jenkins/build.sh
  pom.xml
  src/resources/streamnative/checkstyle.xml
  src/resources/streamnative/findbugsExclude.xml
  src/resources/streamnative/suppressions.xml
Labels: area/build, type/cleanup

#12 Fix release badge and add bintray & jenkins badges
  README.md
Labels: area/doc, type/bug

#13 Update README with artifact on Bintray
  README.md
Labels: area/doc, type/task

#14 Cleanup build warnings
  .jenkins/build.sh
  pom.xml
  src/test/scala/org/apache/spark/sql/pulsar/PulsarContinuousTest.scala
  src/test/scala/org/apache/spark/sql/pulsar/SchemaData.scala
Labels: area/build, type/cleanup

#16 Enable scalastyle check
  .jenkins/build.sh
  pom.xml
  src/main/scala/org/apache/spark/sql/pulsar/CachedPulsarClient.scala
  src/main/scala/org/apache/spark/sql/pulsar/JSONParser.scala
  src/main/scala/org/apache/spark/sql/pulsar/JsonUtils.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarConfigUpdater.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarDeserializer.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarOffset.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarOptions.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarRelation.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarSerializer.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarSinks.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarSource.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarSourceRDD.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarSources.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarStreamWriter.scala
  src/main/scala/org/apache/spark/sql/pulsar/PulsarWriteTask.scala
  src/main/scala/org/apache/spark/sql/pulsar/SchemaUtils.scala
  src/main/scala/org/apache/spark/sql/pulsar/package.scala
  src/resources/scalastyle-config.xml
  src/test/scala/org/apache/spark/sql/pulsar/AvroSchemaSuite.scala
  src/test/scala/org/apache/spark/sql/pulsar/JsonUtilsTestSuite.scala
  src/test/scala/org/apache/spark/sql/pulsar/PulsarContinuousSinkSuite.scala
  src/test/scala/org/apache/spark/sql/pulsar/PulsarContinuousSourceSuite.scala
  src/test/scala/org/apache/spark/sql/pulsar/PulsarContinuousTest.scala
  src/test/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchSourceSuite.scala
  src/test/scala/org/apache/spark/sql/pulsar/PulsarRelationSuite.scala
  src/test/scala/org/apache/spark/sql/pulsar/PulsarSinkSuite.scala
  src/test/scala/org/apache/spark/sql/pulsar/PulsarSourceOffsetSuite.scala
  src/test/scala/org/apache/spark/sql/pulsar/PulsarSourceSuiteBase.scala
  src/test/scala/org/apache/spark/sql/pulsar/PulsarSourceTest.scala
  src/test/scala/org/apache/spark/sql/pulsar/PulsarTest.scala
  src/test/scala/org/apache/spark/sql/pulsar/SchemaData.scala
Labels: type/cleanup
